import { useEffect, useState } from 'react'
import { observer } from 'mobx-react-lite'
import { EditableValueComp, InfoIconWithTooltip, KeyValues, SelectableValueComp } from '@wwf971/react-comp-misc'
import { objectStore, type ObjectPayloadType } from './objectStore'

type ObjectCardProps = {
  spaceId: string
  dataType: ObjectPayloadType
  onRequestSave: (input: { type?: number; editType?: number; valueText?: string; valueJsonText?: string; valueBase64?: string }) => Promise<void> | void
}

const OBJECT_TYPE_MIN = -2147483648
const OBJECT_TYPE_MAX = 2147483647

const EDIT_TYPE_OPTIONS = [
  {
    value: '0',
    label: 'UPDATE-ONLY(0)',
    description: 'Always append next version. In-version write is rejected.',
    compName: 'editTypeOption',
  },
  {
    value: '1',
    label: 'UPDATE-AND-EDIT(1)',
    description: 'Can append next version or rewrite current version.',
    compName: 'editTypeOption',
  },
  {
    value: '2',
    label: 'EDIT-ONLY(2)',
    description: 'Always rewrite current version. Append is rejected.',
    compName: 'editTypeOption',
  },
]

const EditTypeOptionComp = ({ data }: { data: { label?: string; description?: string } }) => {
  return (
    <span className="object-card-edit-type-option">
      <span className="object-card-edit-type-option-label">{data?.label || ''}</span>
      <InfoIconWithTooltip tooltipText={data?.description || ''} width={12} height={12} />
    </span>
  )
}

const ObjectCard = observer(function ObjectCard({
  spaceId,
  dataType,
  onRequestSave,
}: ObjectCardProps) {
  const typeState = objectStore.getSpaceTypeState(spaceId, dataType)!
  const [valueTextInput, setValueTextInput] = useState('')
  const [valueBase64Input, setValueBase64Input] = useState('')
  const [valueJsonTextInput, setValueJsonTextInput] = useState('{}')
  const [typeInputText, setTypeInputText] = useState('-1')
  const [typeErrorText, setTypeErrorText] = useState('')
  const [editTypeInputText, setEditTypeInputText] = useState('0')
  const editingObject = typeState.cardMode === 'edit'
    ? typeState.objectDataById[typeState.cardObjectId] || null
    : null
  useEffect(() => {
    if (typeState.cardMode === 'create') {
      setTypeErrorText('')
      setTypeInputText('-1')
      setEditTypeInputText('0')
      setValueTextInput('')
      setValueBase64Input('')
      setValueJsonTextInput('{}')
      return
    }
    setTypeInputText(String(Number.isFinite(Number(editingObject?.type)) ? Number(editingObject?.type) : -1))
    setTypeErrorText('')
    setEditTypeInputText(String(Number.isFinite(Number(editingObject?.editType)) ? Number(editingObject?.editType) : 0))
    setValueTextInput(String(editingObject?.valueText || ''))
    setValueBase64Input(String(editingObject?.valueBase64 || ''))
    setValueJsonTextInput(editingObject?.valueJson === undefined
      ? '{}'
      : JSON.stringify(editingObject.valueJson, null, 2))
  }, [typeState.cardMode, typeState.cardObjectId, editingObject?.type, editingObject?.editType, editingObject?.valueBase64, editingObject?.valueJson, editingObject?.valueText])
  if (!typeState.isCardVisible) {
    return null
  }
  const isSubmitting = typeState.isCreateOrEditSubmitting
  const selectedEditTypeOption = EDIT_TYPE_OPTIONS.find((item) => item.value === editTypeInputText) || EDIT_TYPE_OPTIONS[0]
  const parseTypeInput = (rawValue: string) => {
    const normalizedText = String(rawValue || '').trim()
    if (!/^-?\d+$/.test(normalizedText)) {
      return {
        isValid: false,
        messageText: 'type should be an integer',
      }
    }
    const parsedValue = Number(normalizedText)
    if (!Number.isFinite(parsedValue)) {
      return {
        isValid: false,
        messageText: 'type should be an integer',
      }
    }
    if (parsedValue < OBJECT_TYPE_MIN || parsedValue > OBJECT_TYPE_MAX) {
      return {
        isValid: false,
        messageText: `type should be within ${OBJECT_TYPE_MIN}..${OBJECT_TYPE_MAX}`,
      }
    }
    return {
      isValid: true,
      value: Math.floor(parsedValue),
      messageText: '',
    }
  }
  return (
    <div className="object-card-overlay" onClick={() => objectStore.closeCard(spaceId, dataType)}>
      <div className="object-card-root" onClick={(event) => event.stopPropagation()}>
        <div className="object-card-title-row">
          <span className="frontend-title">{typeState.cardMode === 'create' ? 'Create Object' : 'Edit Object'}</span>
        </div>
        <div className="frontend-kv">
          <KeyValues
            data={[
              { key: 'spaceId', value: spaceId },
              { key: 'dataType', value: dataType },
              {
                key: 'objectId',
                value: <span className="object-card-id-value">{typeState.cardMode === 'create' ? 'generated by backend' : typeState.cardObjectId}</span>,
              },
            ]}
            isEditable={false}
          />
        </div>
        <div className="object-card-type-row">
          <span className="object-card-type-label">
            <span>type</span>
            <InfoIconWithTooltip
              tooltipText="Semantic object type code, used by client logic."
              width={12}
              height={12}
            />
          </span>
          <EditableValueComp
            data={typeInputText}
            configKey="object.type"
            onUpdate={async (_configKey: string, nextValue: string) => {
              const parsed = parseTypeInput(nextValue)
              if (!parsed.isValid) {
                setTypeErrorText(parsed.messageText)
                return { code: -1, message: parsed.messageText }
              }
              setTypeErrorText('')
              setTypeInputText(String(parsed.value))
              return { code: 0 }
            }}
          />
        </div>
        {typeErrorText ? <div className="frontend-error">{typeErrorText}</div> : null}
        <div className="object-card-type-row">
          <span className="object-card-type-label">
            <span>editType</span>
            <InfoIconWithTooltip
              tooltipText="Object write strategy: append-only, mixed mode, or edit-only."
              width={12}
              height={12}
            />
          </span>
          {typeState.cardMode === 'create' ? (
            <SelectableValueComp
              data={editTypeInputText}
              configKey="object.editType"
              onUpdate={async (_configKey: string, nextValue: string) => {
                setEditTypeInputText(String(nextValue || '0'))
                return { code: 0 }
              }}
              options={EDIT_TYPE_OPTIONS}
              getComp={(compName: string) => (compName === 'editTypeOption' ? EditTypeOptionComp : null)}
            />
          ) : (
            <span className="object-card-edit-type-option">
              <span className="object-card-edit-type-option-label">{selectedEditTypeOption?.label || 'UPDATE-ONLY(0)'}</span>
              <InfoIconWithTooltip tooltipText="Updating editType by API is not supported yet." width={12} height={12} />
            </span>
          )}
        </div>
        {dataType === 'text' ? (
          <textarea
            className="object-card-textarea"
            value={valueTextInput}
            onChange={(event) => setValueTextInput(event.target.value)}
            disabled={isSubmitting}
          />
        ) : null}
        {dataType === 'bytes' ? (
          <textarea
            className="object-card-textarea"
            value={valueBase64Input}
            onChange={(event) => setValueBase64Input(event.target.value)}
            disabled={isSubmitting}
          />
        ) : null}
        {dataType === 'json' ? (
          <textarea
            className="object-card-textarea"
            value={valueJsonTextInput}
            onChange={(event) => setValueJsonTextInput(event.target.value)}
            disabled={isSubmitting}
          />
        ) : null}
        <div className="frontend-actions">
          <button
            type="button"
            className="frontend-btn"
            disabled={isSubmitting}
            onClick={() => objectStore.closeCard(spaceId, dataType)}
          >
            <span>Cancel</span>
          </button>
          <button
            type="button"
            className="frontend-btn"
            disabled={isSubmitting}
            onClick={() => {
              const parsed = parseTypeInput(typeInputText)
              if (!parsed.isValid) {
                setTypeErrorText(parsed.messageText)
                return
              }
              setTypeErrorText('')
              onRequestSave({
                type: parsed.value,
                editType: Number.isFinite(Number(editTypeInputText)) ? Math.floor(Number(editTypeInputText)) : 0,
                valueText: valueTextInput,
                valueBase64: valueBase64Input,
                valueJsonText: valueJsonTextInput,
              })
            }}
          >
            <span>{isSubmitting ? 'Submitting' : 'Save'}</span>
          </button>
        </div>
      </div>
    </div>
  )
})

export default ObjectCard
