dir_base: "."
backend_port: 5107
test_conda_env: ""
database_index: 0

config_dbs:
  local:
    label: local
    host: 127.0.0.1
    port: 5432
    database_name: postgres
    username: postgres
    password: postgres
